apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexushr.fullname" . }}-backend
  labels:
    app: {{ include "nexushr.name" . }}
    component: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nexushr.name" . }}
      component: backend
  template:
    metadata:
      labels:
        app: {{ include "nexushr.name" . }}
        component: backend
    spec:
      containers:
        - name: {{ .Values.backend.name }}
          image: "{{ .Values.backend.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "nexushr.fullname" . }}-config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "nexushr.fullname" . }}-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "nexushr.fullname" . }}-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: NEXUSHR_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "nexushr.fullname" . }}-secrets
                  key: NEXUSHR_JWT_SECRET
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
