apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexushr.fullname" . }}-secrets
  labels:
    app: {{ include "nexushr.name" . }}
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgres.user | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
  NEXUSHR_JWT_SECRET: {{ .Values.backend.env.jwtSecret | b64enc | quote }}
