apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexushr.fullname" . }}-frontend
  labels:
    app: {{ include "nexushr.name" . }}
    component: frontend
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "nexushr.name" . }}
    component: frontend
