apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexushr.fullname" . }}-backend
  labels:
    app: {{ include "nexushr.name" . }}
    component: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "nexushr.name" . }}
    component: backend
